### ISSUE TITLE
5.16 breaks kumk with a double build

### ISSUE THREAD

**Issue by peci1** [k3dar/kumk#2]
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.16/HEADER.html

For some reason, the kernel has been built twice and both versions are in the HEADER.html page. This breaks kumk. However, I'd treat it as a niche case and wouldn't spend time fixing that...

**Comment by k3dar** [comment]
thanks, fix is simple, but before publish i needed first fix other bugs :-)
can you please test latest version?

**Comment by peci1** [comment]
I verified the fix and it works. Thanks!
